### ISSUE TITLE
Version 3.0.5 Problem with PDF files

### ISSUE THREAD

**Issue by HistArchivist** [Daniel-KM/Omeka-S-module-DerivativeImages#3]
The updated version does not seem to work properly on PDF files.

The old derivative images get erased, but no new derivative images are being created.

**Comment by Daniel-KM** [comment]
The process uses the standard process of Omeka. So are derivative files created with new pdf files? In all cases, note that the thumbnailer "gd" cannot create thumbnails for pdf.

**Comment by HistArchivist** [comment]
Sorry to have bothered you. I tried it for 2 days in vain - now it worked like expected.

Thank you for your help - and the module!
