### ISSUE TITLE
Second Page PDF

### ISSUE THREAD

**Issue by rafaeluriarte** [Daniel-KM/Omeka-S-module-DerivativeImages#4]
Maybe it is out of scope of this plugin, but, since the first page of our book scans are always a standard page added by us, we would like to have the second page of each item's PDF as thumbnails. Do you think it could be implemented in this plugin? Thank you

**Comment by rafaeluriarte** [comment]
There was a much easier way - edit this file in Omeka-s dir:
config/local.config.php

and add the page option:
        'thumbnailer_options' => [
		'imagemagick_dir' => null,
		'page' => 1,
        ],
Then you can regenerate all thumbnails with this plugin (leave empty the IDs field and it runs for all media)...

**Comment by Daniel-KM** [comment]
Ok, thanks for the info.
